FROM clojure:lein-alpine
WORKDIR /usr/src/app

VOLUME ["/puppet", "/hiera", "/facter", "/etc/puppetlabs/puppetserver/conf.d", "/opt/puppetlabs/server/data/puppetserver/jruby-gems"]

COPY . /usr/src/app/

COPY docker/puppetserver-standalone/logback.xml /etc/puppetlabs/puppetserver/
COPY docker/puppetserver-standalone/request-logging.xml /etc/puppetlabs/puppetserver/

RUN apk add --no-cache make && \
    apk add --no-cache java-jffi-native libc6-compat shadow && \
    mkdir -p /var/run/puppetlabs/puppetserver /var/log/puppetlabs/puppetserver

EXPOSE 8140

CMD lein run -b /etc/puppetlabs/puppetserver/bootstrap.cfg,/etc/puppetlabs/puppetserver/services.d -c /etc/puppetlabs/puppetserver/conf.d
